# frozen_string_literal: true

# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure('2') do |config|
  config.vm.provider 'docker' do |d|
    d.build_dir = '.'
    d.has_ssh = true
  end

  config.ssh.username = 'vagrant'
  config.ssh.password = 'vagrant'
  config.ssh.insert_key = false

  config.vm.network 'forwarded_port', guest: 5000, host: 1234
  config.vm.network 'forwarded_port', guest: 8000, host: 8000
  config.vm.network 'forwarded_port', guest: 8080, host: 8080
  config.vm.network 'forwarded_port', guest: 22, host: 2222

  config.vm.synced_folder '.', '/vagrant', SharedFoldersEnableSymlinksCreate: false

  # Add a shell provisioner to bypass the /etc/fstab error
  # config.vm.provision 'shell', inline: <<-SHELL
  # This script is run after the container is created to handle
  # any necessary setup that cannot be done in the Dockerfile.
  # echo 'Custom provisioner running'
  # Comment out the sed command to avoid error
  # sed -i '/#VAGRANT-BEGIN/,/#VAGRANT-END/d' /etc/fstab || true
  # SHELL
end
