# frozen_string_literal: true

# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure('2') do |config|
  config.vm.provider 'docker' do |d|
    d.build_dir = '.'
    d.has_ssh = true
  end

  config.ssh.username = 'vagrant'
  config.ssh.password = 'vagrant'
  config.ssh.insert_key = false

  config.vm.network 'forwarded_port', guest: 5432, host: 15_432
  config.vm.network 'forwarded_port', guest: 8000, host: 18_000
  config.vm.network 'forwarded_port', guest: 8080, host: 18_080
  config.vm.network 'forwarded_port', guest: 5000, host: 15_000

  config.vm.synced_folder '.', '/vagrant', SharedFoldersEnableSymlinksCreate: false
end
